Feat typescript frontend
linux-odyssey/linux-odyssey pull request #107
Opened 2024-02-27 02:28 UTC by NeilChen0812

2024-02-27 03:18 UTC, lancatlin requested changes
Prevent using `any` as type. Define interface for the axios request and response. Ref: https://bobbyhadz.com/blog/typescript-http-request-axios

2024-02-27 03:18 UTC, lancatlin commented on app/src/utils/errors.ts
> +  constructor(message: string | undefined) {
You can simply use optional parameter:
```suggestion
  constructor(message?: string) {
```

2024-02-27 03:18 UTC, lancatlin commented on app/src/utils/socket.ts
> +  socket: any
Find the correct type for socket.io client

2024-02-28 07:34 UTC, Annie04082020 commented
Remember to change type "any" to specify ones

2024-03-28 13:20 UTC, lancatlin approved these changes

2024-03-28 13:22 UTC, merged