feat: hint part
linux-odyssey/linux-odyssey pull request #27
Opened 2023-09-17 13:07 UTC by Annie04082020

Redo the hint part due to the socket method update

2023-09-18 04:53 UTC, Annie04082020 commented on app/src/utils/session.js
ref([ ])

2023-09-18 04:54 UTC, Annie04082020 commented on app/src/utils/session.js
Delete if

2023-09-18 15:56 UTC, lancatlin requested changes
Please rebase main as well

2023-09-18 15:56 UTC, lancatlin commented on app/src/components/HintPart.vue
> +    </li>
Implement using pager, letting user focus on current hint only.

2023-09-27 15:29 UTC, Annie04082020 commented
rebase branch is opened in another pull request

2023-09-27 15:29 UTC, closed without merging