Feat automation test
linux-odyssey/linux-odyssey pull request #47
Opened 2023-10-28 10:01 UTC by Annie04082020

Add cypress automation tests

- Verify Login and Register UI
- Not yet login using Google and GitHub
- Add json file for entering command and verify the story is end
- Verify Game Starting UI
- Verify Game Play (including stage secret)

2023-10-28 15:02 UTC, lancatlin requested changes

2023-10-28 15:10 UTC, Annie04082020 commented on tests/.env
I'm sorry that I didn't consider about this

2023-11-12 09:29 UTC, Annie04082020 commented on tests/cypress/e2e/helloworld.cy.js
> +      cy.findByRole('button', { name: 'Reset' }).should('be.visible')
Verifying element should be seperated and not able to filter and verify at the same time, so I'll keep it as the previous version.

2023-11-13 12:44 UTC, lancatlin commented
Please re-open this PR in a new branch

2023-11-13 12:44 UTC, closed without merging